"""Learning package public exports."""

from .engine import (
	LearningUpdateResult,
	LearningSnapshot,
	PhaseShiftSignal,
	SchemaEvaluation,
	WeightPlateauSignal,
	apply_schema_proposal_if_approved,
	apply_learning_updates,
	SchemaProposal,
	aggregate_residuals_by_mechanism,
	decay_weak_fields,
	detect_weight_plateau,
	detect_phase_shift,
	derive_learning_snapshot,
	derive_retrieval_weights,
	evaluate_schema_proposal,
	evaluate_schema_proposal_on_history,
	load_residual_frame,
	log_schedule_selection,
	materialize_schema_field_backfill,
	propose_schema_growth_with_llm,
	record_schema_decision,
	propose_schema_growth,
)

__all__ = [
	"LearningUpdateResult",
	"LearningSnapshot",
	"PhaseShiftSignal",
	"SchemaEvaluation",
	"WeightPlateauSignal",
	"apply_schema_proposal_if_approved",
	"apply_learning_updates",
	"SchemaProposal",
	"aggregate_residuals_by_mechanism",
	"decay_weak_fields",
	"detect_weight_plateau",
	"detect_phase_shift",
	"derive_learning_snapshot",
	"derive_retrieval_weights",
	"evaluate_schema_proposal",
	"evaluate_schema_proposal_on_history",
	"load_residual_frame",
	"log_schedule_selection",
	"materialize_schema_field_backfill",
	"propose_schema_growth_with_llm",
	"record_schema_decision",
	"propose_schema_growth",
]
