-- CADEN SQLite Schema
-- All timestamps stored as ISO 8601 strings

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ─── Settings key-value store ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY NOT NULL,
    value TEXT
);

-- ─── Google Calendar events cache ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events_cache (
    id            TEXT PRIMARY KEY NOT NULL,
    title         TEXT NOT NULL,
    start_time    TEXT NOT NULL,
    end_time      TEXT NOT NULL,
    all_day       INTEGER NOT NULL DEFAULT 0,
    calendar_name TEXT NOT NULL DEFAULT '',
    fetched_at    TEXT NOT NULL
);

-- ─── Tasks cache (Google Tasks + Moodle assignments) ────────────────────────
CREATE TABLE IF NOT EXISTS tasks_cache (
    id          TEXT PRIMARY KEY NOT NULL,
    title       TEXT NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('tasks', 'moodle')),
    due_date    TEXT,
    completed   INTEGER NOT NULL DEFAULT 0,
    notes       TEXT,
    list_name   TEXT,
    course_name TEXT,
    fetched_at  TEXT NOT NULL
);

-- ─── Daily plans (generated by the planner) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_plans (
    id              TEXT PRIMARY KEY NOT NULL,
    date            TEXT NOT NULL,
    task_id         TEXT NOT NULL,
    source          TEXT NOT NULL,
    title           TEXT NOT NULL,
    scheduled_start TEXT,
    scheduled_end   TEXT,
    urgency_score   REAL NOT NULL DEFAULT 0,
    effort_weight   REAL NOT NULL DEFAULT 3,
    completed       INTEGER NOT NULL DEFAULT 0,
    completed_at    TEXT,
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_daily_plans_date ON daily_plans(date);

-- ─── Completions log ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS completions (
    id           TEXT PRIMARY KEY NOT NULL,
    task_id      TEXT NOT NULL,
    source       TEXT NOT NULL,
    planned_time TEXT,
    actual_time  TEXT NOT NULL,
    plan_date    TEXT NOT NULL
);

-- ─── Skips log ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skips (
    id        TEXT PRIMARY KEY NOT NULL,
    task_id   TEXT NOT NULL,
    source    TEXT NOT NULL,
    reason    TEXT,
    timestamp TEXT NOT NULL
);

-- ─── Pattern learning ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS patterns (
    id                   TEXT PRIMARY KEY NOT NULL,
    task_type            TEXT NOT NULL,
    time_of_day          TEXT NOT NULL, -- 'morning', 'afternoon', 'evening'
    completion_rate      REAL NOT NULL DEFAULT 0,
    avg_delay_minutes    REAL NOT NULL DEFAULT 0,
    sample_count         INTEGER NOT NULL DEFAULT 0,
    last_updated         TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_patterns_type_time
    ON patterns(task_type, time_of_day);

-- ─── User corrections / preference log ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_corrections (
    id              TEXT PRIMARY KEY NOT NULL,
    correction_type TEXT NOT NULL,    -- 'task_reorder', 'preference', etc.
    description     TEXT NOT NULL,
    data            TEXT,             -- JSON payload
    timestamp       TEXT NOT NULL
);
