-- CADEN SQLite Schema
-- All timestamps stored as ISO 8601 strings

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ─── Settings key-value store ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY NOT NULL,
    value TEXT
);

-- ─── Google Calendar events cache ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events_cache (
    id            TEXT PRIMARY KEY NOT NULL,
    title         TEXT NOT NULL,
    start_time    TEXT NOT NULL,
    end_time      TEXT NOT NULL,
    all_day       INTEGER NOT NULL DEFAULT 0,
    calendar_name TEXT NOT NULL DEFAULT '',
    fetched_at    TEXT NOT NULL
);

-- ─── Tasks cache (Google Tasks + Moodle assignments) ────────────────────────
CREATE TABLE IF NOT EXISTS tasks_cache (
    id          TEXT PRIMARY KEY NOT NULL,
    title       TEXT NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('tasks', 'moodle')),
    due_date    TEXT,
    completed   INTEGER NOT NULL DEFAULT 0,
    notes       TEXT,
    list_name   TEXT,
    course_name TEXT,
    fetched_at  TEXT NOT NULL
);

-- ─── Daily plans (generated by the planner) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_plans (
    id              TEXT PRIMARY KEY NOT NULL,
    date            TEXT NOT NULL,
    task_id         TEXT NOT NULL,
    source          TEXT NOT NULL,
    title           TEXT NOT NULL,
    scheduled_start TEXT,
    scheduled_end   TEXT,
    urgency_score   REAL NOT NULL DEFAULT 0,
    effort_weight   REAL NOT NULL DEFAULT 3,
    completed       INTEGER NOT NULL DEFAULT 0,
    completed_at    TEXT,
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_daily_plans_date ON daily_plans(date);

-- ─── Completions log ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS completions (
    id           TEXT PRIMARY KEY NOT NULL,
    task_id      TEXT NOT NULL,
    source       TEXT NOT NULL,
    planned_time TEXT,
    actual_time  TEXT NOT NULL,
    plan_date    TEXT NOT NULL
);

-- ─── Skips log ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skips (
    id        TEXT PRIMARY KEY NOT NULL,
    task_id   TEXT NOT NULL,
    source    TEXT NOT NULL,
    reason    TEXT,
    timestamp TEXT NOT NULL
);

-- ─── Pattern learning ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS patterns (
    id                   TEXT PRIMARY KEY NOT NULL,
    task_type            TEXT NOT NULL,
    time_of_day          TEXT NOT NULL, -- 'morning', 'afternoon', 'evening'
    completion_rate      REAL NOT NULL DEFAULT 0,
    avg_delay_minutes    REAL NOT NULL DEFAULT 0,
    sample_count         INTEGER NOT NULL DEFAULT 0,
    last_updated         TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_patterns_type_time
    ON patterns(task_type, time_of_day);

-- ─── Projects (long-term work / knowledge base) ─────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
    id          TEXT PRIMARY KEY NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    status      TEXT NOT NULL DEFAULT 'active', -- active, paused, completed, archived
    folder_path TEXT,
    parent_id   TEXT REFERENCES projects(id) ON DELETE SET NULL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);

CREATE TABLE IF NOT EXISTS project_entries (
    id          TEXT PRIMARY KEY NOT NULL,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    entry_type  TEXT NOT NULL DEFAULT 'note', -- todo, update, decision, idea, blocker, reference
    content     TEXT NOT NULL,
    tags        TEXT,
    completed   INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    embedding   BLOB  -- nomic-embed-text vector, stored as little-endian f32 bytes
);

CREATE INDEX IF NOT EXISTS idx_project_entries_project ON project_entries(project_id);

-- ─── Plugin registry ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS plugins (
    id          TEXT PRIMARY KEY NOT NULL,
    name        TEXT NOT NULL,
    folder_path TEXT NOT NULL,
    entry       TEXT NOT NULL DEFAULT '',
    dev_url     TEXT,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL
);

-- ─── User corrections / preference log ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_corrections (
    id              TEXT PRIMARY KEY NOT NULL,
    correction_type TEXT NOT NULL,    -- 'task_reorder', 'preference', etc.
    description     TEXT NOT NULL,
    data            TEXT,             -- JSON payload
    timestamp       TEXT NOT NULL
);

-- ─── Sean Model: circadian energy grid (24 hours × 7 days) ──────────────────
-- Tracks how productive Sean is at each hour of the week.
-- Updated whenever a task is completed or skipped.
CREATE TABLE IF NOT EXISTS circadian_model (
    hour        INTEGER NOT NULL CHECK(hour >= 0 AND hour <= 23),
    day_of_week INTEGER NOT NULL CHECK(day_of_week >= 0 AND day_of_week <= 6), -- 0=Mon
    completions INTEGER NOT NULL DEFAULT 0,
    samples     INTEGER NOT NULL DEFAULT 0,
    last_updated TEXT NOT NULL,
    PRIMARY KEY (hour, day_of_week)
);

-- ─── Sean Model: behavioral event log ────────────────────────────────────────
-- Fine-grained log used for flow state detection and spike analysis.
CREATE TABLE IF NOT EXISTS behavioral_log (
    id              TEXT PRIMARY KEY NOT NULL,
    event_type      TEXT NOT NULL,   -- 'completion', 'skip', 'flow_window'
    task_type       TEXT,
    hour            INTEGER,
    day_of_week     INTEGER,
    duration_minutes INTEGER,
    timestamp       TEXT NOT NULL
);

-- ─── Sean Model: chat log ────────────────────────────────────────────────────
-- Every message Sean sends to CADEN is stored here with its embedding.
-- Only user-role messages — CADEN's responses are not stored (this is about
-- learning Sean, not CADEN). Over time this becomes a searchable record of
-- everything Sean has expressed, asked, or worried about.
CREATE TABLE IF NOT EXISTS chat_log (
    id          TEXT PRIMARY KEY NOT NULL,
    content     TEXT NOT NULL,
    embedding   BLOB,               -- nomic-embed-text vector (f32 LE bytes)
    timestamp   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_log_timestamp ON chat_log(timestamp);

-- ─── Web search cache (cited results with embeddings) ────────────────────────
-- Every URL CADEN looks up is stored here so it can be cited and revisited.
-- Embeddings enable semantic recall ("find what I searched about X before").
CREATE TABLE IF NOT EXISTS web_search_cache (
    id          TEXT PRIMARY KEY NOT NULL,
    query       TEXT NOT NULL,
    url         TEXT NOT NULL,
    title       TEXT NOT NULL,
    snippet     TEXT,
    content     TEXT,       -- fetched page text, truncated to ~4000 chars
    embedding   BLOB,       -- nomic-embed-text vector (f32 LE bytes)
    searched_at TEXT NOT NULL,
    accessed_at TEXT        -- last time CADEN re-referenced this URL
);

CREATE INDEX IF NOT EXISTS idx_web_search_query ON web_search_cache(query);
CREATE INDEX IF NOT EXISTS idx_web_search_url   ON web_search_cache(url);
